name: 'Terraform'

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    # 1Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2
    
           
    - name: Setup AWS ceredentials 
      uses: aws-actions/configure-aws-credentials@v1
      with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
           aws-session-token: ${{ secrets.AWS_TOKEN }}         
       
          
    - name: Deploy to AWS CloudFormation
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: MyStack
        template: 1_infrastructure/aws/cloudformation/vpcinfra.yaml
        parameter-overrides: "VpcCIDR=10.0.0.0/16,PublicSubnet1CIDR=10.0.0.0/24,PublicSubnet2CIDR=10.0.1.0/24,PrivateSubnet1CIDR=10.0.2.0/24,PrivateSubnet2CIDR=10.0.3.0/24,PrivateSubnet3CIDR=10.0.4.0/24,PrivateSubnet4CIDR=10.0.5.0/24,SSHLocation=0.0.0.0/0,BastionInstanceType=t2.micro,EC2KeyName=tintest"
